// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://xkynqxckgzewryzzzfgc.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhreW5xeGNrZ3pld3J5enp6ZmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0Njg1NjEsImV4cCI6MjA4MTA0NDU2MX0.YdtRrlGSKERTTGNLXv5b_OJ9vCe1_7_ZobTiCdezcUU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(supabaseUrl, supabaseAnonKey);