// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://nqwsddelffmntecsvzsb.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xd3NkZGVsZmZtbnRlY3N2enNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Njk1NjMsImV4cCI6MjA2NzQ0NTU2M30._nJdKK1gRonBuIMT6Q5ycisz21EwY-GSLl64wk5T5tA';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(supabaseUrl, supabaseAnonKey);