// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://uhgwqjpurycptnctudde.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoZ3dxanB1cnljcHRuY3R1ZGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjExOTQsImV4cCI6MjA3MDkzNzE5NH0.SVAMErB1bqQrIS4KpSKDuKkXMJFY21Rswr6KnradIUk';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(supabaseUrl, supabaseAnonKey);